language: rust

addons:
  apt:
    packages:
      - libasound2-dev
      - libxxf86vm-dev
      - libosmesa6-dev
      - libssl-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - stage: "Coverage"
      rust: beta # https://github.com/rust-lang/rust/issues/52478
      script:
        - cargo install cargo-tarpaulin -f
        - cargo tarpaulin --out Xml
        - bash <(curl -s https://codecov.io/bash)

cache: cargo

before_script:
  - rustup component add rustfmt

script:
  - cargo build --all --verbose
  - cargo build --all --release --verbose
  - cargo test --all --verbose
  - cargo test --all --release --verbose
  - cargo fmt --all -- --check
