[package]
name = "plitki-core"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[dependencies]
circular-queue = "0.2"

[dev-dependencies]
criterion = "0.7"
proptest = "1"
proptest-derive = "0.6"

[[bench]]
name = "visibility_cache"
harness = false
