[package]
name = "plitki-core"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[dependencies]
circular-queue = "0.2.6"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
