[package]
name = "plitki-core"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[dependencies]
# The git version has fixed no_std.
derive_more = { git = "https://github.com/JelteF/derive_more.git" }

[dev-dependencies]
proptest = "0.9.4"
