[package]
name = "plitki-core"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[dependencies]
circular-queue = "0.2.6"

[dev-dependencies]
criterion = "0.4.0"
proptest = "1.0.0"
proptest-derive = "0.3.0"

[[bench]]
name = "visibility_cache"
harness = false
